export { default as HeroSection } from './HeroSection';
export { default as FeaturesGrid } from './FeaturesGrid';
export { default as Testimonials } from './Testimonials';
export { default as PricingCards } from './PricingCards';
export { default as Comparison } from './Comparison';
export { ComparisonTable } from './ComparisonTable';
export { default as FAQSection } from './FAQSection';
export { default as SmartHomeSection } from './SmartHomeSection';
export { default as SmartLifeSection } from './SmartLifeSection';
export { default as AdhdFriendlySection } from './AdhdFriendlySection';
export { default as IntegrationsSection } from './IntegrationsSection';
