import type { EmojiCategoryDefinition, EmojiDefinition } from './types';

export const EMOJI_CATEGORIES: EmojiCategoryDefinition[] = [
  { id: 'smileys', label: 'Smileys', icon: '😀' },
  { id: 'people', label: 'People', icon: '👋' },
  { id: 'nature', label: 'Nature', icon: '🌿' },
  { id: 'food', label: 'Food', icon: '🍎' },
  { id: 'travel', label: 'Travel', icon: '✈️' },
  { id: 'activities', label: 'Activities', icon: '⚽' },
  { id: 'objects', label: 'Objects', icon: '💡' },
  { id: 'symbols', label: 'Symbols', icon: '❤️' },
];

const item = (
  id: string,
  emoji: string,
  name: string,
  category: EmojiDefinition['category'],
  keywords: string[],
  skinTones?: EmojiDefinition['skinTones'],
): EmojiDefinition => ({
  id,
  emoji,
  name,
  category,
  keywords,
  skinTones,
});

export const EMOJI_DEFINITIONS: EmojiDefinition[] = [
  item('grinning_face', '😀', 'grinning face', 'smileys', ['smile', 'happy', 'joy']),
  item('smile', '😄', 'smile', 'smileys', ['happy', 'joy', 'cheerful']),
  item('tears_of_joy', '😂', 'tears of joy', 'smileys', ['lol', 'laugh', 'tears']),
  item('wink', '😉', 'wink', 'smileys', ['playful', 'flirt']),
  item('blush', '😊', 'blush', 'smileys', ['warm', 'kind', 'friendly']),
  item('heart_eyes', '😍', 'heart eyes', 'smileys', ['love', 'adore']),
  item('thinking_face', '🤔', 'thinking face', 'smileys', ['think', 'question']),
  item('neutral_face', '😐', 'neutral face', 'smileys', ['meh', 'neutral']),
  item('cry', '😢', 'cry', 'smileys', ['sad', 'tears']),
  item('angry', '😠', 'angry', 'smileys', ['mad', 'upset']),
  item('party_face', '🥳', 'party face', 'smileys', ['party', 'celebration']),

  item(
    'waving_hand',
    '👋',
    'waving hand',
    'people',
    ['hello', 'wave', 'greeting'],
    {
      light: '👋🏻',
      'medium-light': '👋🏼',
      medium: '👋🏽',
      'medium-dark': '👋🏾',
      dark: '👋🏿',
    },
  ),
  item(
    'thumbs_up',
    '👍',
    'thumbs up',
    'people',
    ['ok', 'approve', 'yes'],
    {
      light: '👍🏻',
      'medium-light': '👍🏼',
      medium: '👍🏽',
      'medium-dark': '👍🏾',
      dark: '👍🏿',
    },
  ),
  item(
    'thumbs_down',
    '👎',
    'thumbs down',
    'people',
    ['no', 'disapprove', 'down'],
    {
      light: '👎🏻',
      'medium-light': '👎🏼',
      medium: '👎🏽',
      'medium-dark': '👎🏾',
      dark: '👎🏿',
    },
  ),
  item(
    'clapping_hands',
    '👏',
    'clapping hands',
    'people',
    ['applause', 'clap'],
    {
      light: '👏🏻',
      'medium-light': '👏🏼',
      medium: '👏🏽',
      'medium-dark': '👏🏾',
      dark: '👏🏿',
    },
  ),
  item(
    'raising_hands',
    '🙌',
    'raising hands',
    'people',
    ['hooray', 'celebrate', 'praise'],
    {
      light: '🙌🏻',
      'medium-light': '🙌🏼',
      medium: '🙌🏽',
      'medium-dark': '🙌🏾',
      dark: '🙌🏿',
    },
  ),
  item(
    'folded_hands',
    '🙏',
    'folded hands',
    'people',
    ['thanks', 'pray', 'please'],
    {
      light: '🙏🏻',
      'medium-light': '🙏🏼',
      medium: '🙏🏽',
      'medium-dark': '🙏🏾',
      dark: '🙏🏿',
    },
  ),
  item(
    'ok_hand',
    '👌',
    'ok hand',
    'people',
    ['ok', 'perfect', 'hand'],
    {
      light: '👌🏻',
      'medium-light': '👌🏼',
      medium: '👌🏽',
      'medium-dark': '👌🏾',
      dark: '👌🏿',
    },
  ),
  item(
    'muscle',
    '💪',
    'flexed biceps',
    'people',
    ['strong', 'gym', 'power'],
    {
      light: '💪🏻',
      'medium-light': '💪🏼',
      medium: '💪🏽',
      'medium-dark': '💪🏾',
      dark: '💪🏿',
    },
  ),
  item(
    'writing_hand',
    '✍️',
    'writing hand',
    'people',
    ['write', 'note', 'draft'],
    {
      light: '✍🏻',
      'medium-light': '✍🏼',
      medium: '✍🏽',
      'medium-dark': '✍🏾',
      dark: '✍🏿',
    },
  ),
  item('technologist', '🧑‍💻', 'technologist', 'people', ['developer', 'computer', 'code']),
  item('teacher', '🧑‍🏫', 'teacher', 'people', ['school', 'teach', 'education']),
  item('office_worker', '🧑‍💼', 'office worker', 'people', ['business', 'work']),
  item('man', '👨', 'man', 'people', ['person', 'male']),
  item('woman', '👩', 'woman', 'people', ['person', 'female']),
  item('family', '👨‍👩‍👧‍👦', 'family', 'people', ['parents', 'kids', 'home']),
  item('group', '👥', 'group', 'people', ['team', 'community']),

  item('seedling', '🌱', 'seedling', 'nature', ['plant', 'growth', 'green']),
  item('tree', '🌳', 'tree', 'nature', ['forest', 'nature']),
  item('palm_tree', '🌴', 'palm tree', 'nature', ['tropical', 'vacation']),
  item('clover', '🍀', 'four leaf clover', 'nature', ['luck', 'plant']),
  item('leaf', '🍃', 'leaf fluttering in wind', 'nature', ['wind', 'leaf']),
  item('sunflower', '🌻', 'sunflower', 'nature', ['flower', 'sun']),
  item('rose', '🌹', 'rose', 'nature', ['flower', 'love']),
  item('earth', '🌎', 'globe americas', 'nature', ['earth', 'world']),
  item('sun', '☀️', 'sun', 'nature', ['sunny', 'weather']),
  item('moon', '🌙', 'crescent moon', 'nature', ['night', 'moon']),
  item('cloud', '☁️', 'cloud', 'nature', ['weather']),
  item('rain', '🌧️', 'cloud with rain', 'nature', ['rain', 'weather']),
  item('snowflake', '❄️', 'snowflake', 'nature', ['winter', 'cold']),
  item('fire', '🔥', 'fire', 'nature', ['hot', 'lit']),
  item('wave', '🌊', 'water wave', 'nature', ['sea', 'ocean']),
  item('dog', '🐶', 'dog face', 'nature', ['pet', 'animal']),
  item('cat', '🐱', 'cat face', 'nature', ['pet', 'animal']),

  item('green_apple', '🍏', 'green apple', 'food', ['fruit', 'apple']),
  item('apple', '🍎', 'red apple', 'food', ['fruit', 'apple']),
  item('banana', '🍌', 'banana', 'food', ['fruit']),
  item('grapes', '🍇', 'grapes', 'food', ['fruit']),
  item('strawberry', '🍓', 'strawberry', 'food', ['fruit']),
  item('watermelon', '🍉', 'watermelon', 'food', ['fruit']),
  item('cherries', '🍒', 'cherries', 'food', ['fruit']),
  item('avocado', '🥑', 'avocado', 'food', ['fruit', 'healthy']),
  item('pizza', '🍕', 'pizza', 'food', ['meal', 'fast food']),
  item('hamburger', '🍔', 'hamburger', 'food', ['burger', 'meal']),
  item('fries', '🍟', 'french fries', 'food', ['fries', 'snack']),
  item('taco', '🌮', 'taco', 'food', ['mexican']),
  item('sushi', '🍣', 'sushi', 'food', ['japanese']),
  item('cake', '🍰', 'shortcake', 'food', ['dessert']),
  item('birthday', '🎂', 'birthday cake', 'food', ['birthday', 'celebration']),
  item('coffee', '☕', 'hot coffee', 'food', ['drink', 'cafe']),
  item('tea', '🍵', 'tea', 'food', ['drink']),
  item('cocktail', '🍸', 'cocktail glass', 'food', ['drink', 'party']),

  item('map', '🗺️', 'world map', 'travel', ['map', 'travel']),
  item('compass', '🧭', 'compass', 'travel', ['direction', 'navigation']),
  item('airplane', '✈️', 'airplane', 'travel', ['flight', 'travel']),
  item('airplane_departure', '🛫', 'airplane departure', 'travel', ['airport']),
  item('airplane_arrival', '🛬', 'airplane arrival', 'travel', ['airport']),
  item('rocket', '🚀', 'rocket', 'travel', ['space', 'launch']),
  item('car', '🚗', 'automobile', 'travel', ['car', 'vehicle']),
  item('taxi', '🚕', 'taxi', 'travel', ['cab']),
  item('bus', '🚌', 'bus', 'travel', ['public transport']),
  item('train', '🚆', 'train', 'travel', ['rail']),
  item('ferry', '⛴️', 'ferry', 'travel', ['boat']),
  item('ship', '🚢', 'ship', 'travel', ['cruise', 'boat']),
  item('bicycle', '🚲', 'bicycle', 'travel', ['bike', 'cycling']),
  item('motorcycle', '🏍️', 'motorcycle', 'travel', ['bike']),
  item('luggage', '🧳', 'luggage', 'travel', ['trip', 'bag']),
  item('camping', '🏕️', 'camping', 'travel', ['tent', 'outdoor']),
  item('beach', '🏖️', 'beach with umbrella', 'travel', ['vacation', 'sea']),
  item('cityscape', '🌆', 'cityscape', 'travel', ['city', 'urban']),
  item('hotel', '🏨', 'hotel', 'travel', ['stay', 'room']),

  item('soccer', '⚽', 'soccer ball', 'activities', ['sport', 'football']),
  item('basketball', '🏀', 'basketball', 'activities', ['sport']),
  item('baseball', '⚾', 'baseball', 'activities', ['sport']),
  item('tennis', '🎾', 'tennis', 'activities', ['sport']),
  item('volleyball', '🏐', 'volleyball', 'activities', ['sport']),
  item('rugby', '🏉', 'rugby football', 'activities', ['sport']),
  item('golf', '⛳', 'flag in hole', 'activities', ['golf', 'sport']),
  item('ping_pong', '🏓', 'ping pong', 'activities', ['table tennis']),
  item('badminton', '🏸', 'badminton', 'activities', ['sport']),
  item('boxing_glove', '🥊', 'boxing glove', 'activities', ['sport', 'fight']),
  item('meditation', '🧘', 'person in lotus position', 'activities', ['yoga', 'mindfulness']),
  item('video_game', '🎮', 'video game', 'activities', ['gaming', 'console']),
  item('joystick', '🕹️', 'joystick', 'activities', ['game']),
  item('musical_note', '🎵', 'musical note', 'activities', ['music']),
  item('microphone', '🎤', 'microphone', 'activities', ['karaoke', 'music']),
  item('guitar', '🎸', 'guitar', 'activities', ['music']),
  item('movie_camera', '🎥', 'movie camera', 'activities', ['film', 'video']),
  item('performing_arts', '🎭', 'performing arts', 'activities', ['theater']),
  item('art_palette', '🎨', 'artist palette', 'activities', ['art', 'painting']),

  item('light_bulb', '💡', 'light bulb', 'objects', ['idea', 'inspiration']),
  item('memo', '📝', 'memo', 'objects', ['note', 'write']),
  item('clipboard', '📋', 'clipboard', 'objects', ['task', 'checklist']),
  item('calendar', '📅', 'calendar', 'objects', ['date', 'schedule']),
  item('spiral_calendar', '🗓️', 'spiral calendar', 'objects', ['date', 'plan']),
  item('alarm_clock', '⏰', 'alarm clock', 'objects', ['time', 'reminder']),
  item('hourglass', '⌛', 'hourglass', 'objects', ['time', 'wait']),
  item('watch', '⌚', 'watch', 'objects', ['time']),
  item('mobile_phone', '📱', 'mobile phone', 'objects', ['phone']),
  item('laptop', '💻', 'laptop', 'objects', ['computer']),
  item('desktop', '🖥️', 'desktop computer', 'objects', ['computer']),
  item('printer', '🖨️', 'printer', 'objects', ['office']),
  item('camera', '📷', 'camera', 'objects', ['photo']),
  item('video_camera', '📹', 'video camera', 'objects', ['recording']),
  item('mailbox', '📫', 'mailbox', 'objects', ['mail']),
  item('link', '🔗', 'link', 'objects', ['url', 'connection']),
  item('paperclip', '📎', 'paperclip', 'objects', ['attach']),
  item('pushpin', '📌', 'pushpin', 'objects', ['pin']),
  item('money_bag', '💰', 'money bag', 'objects', ['finance', 'budget']),
  item('chart', '📊', 'bar chart', 'objects', ['analytics', 'stats']),

  item('check_mark', '✅', 'check mark button', 'symbols', ['done', 'success']),
  item('cross_mark', '❌', 'cross mark', 'symbols', ['close', 'error']),
  item('warning', '⚠️', 'warning', 'symbols', ['alert', 'danger']),
  item('information', 'ℹ️', 'information', 'symbols', ['info']),
  item('question', '❓', 'question mark', 'symbols', ['help']),
  item('exclamation', '❗', 'exclamation mark', 'symbols', ['important']),
  item('heavy_plus_sign', '➕', 'plus', 'symbols', ['add']),
  item('heavy_minus_sign', '➖', 'minus', 'symbols', ['remove']),
  item('divide', '➗', 'divide', 'symbols', ['math']),
  item('multiply', '✖️', 'multiply', 'symbols', ['math']),
  item('red_heart', '❤️', 'red heart', 'symbols', ['love']),
  item('orange_heart', '🧡', 'orange heart', 'symbols', ['heart']),
  item('yellow_heart', '💛', 'yellow heart', 'symbols', ['heart']),
  item('green_heart', '💚', 'green heart', 'symbols', ['heart']),
  item('blue_heart', '💙', 'blue heart', 'symbols', ['heart']),
  item('purple_heart', '💜', 'purple heart', 'symbols', ['heart']),
  item('black_heart', '🖤', 'black heart', 'symbols', ['heart']),
  item('sparkles', '✨', 'sparkles', 'symbols', ['shine', 'magic']),
  item('star', '⭐', 'star', 'symbols', ['favorite']),
  item('bullseye', '🎯', 'direct hit', 'symbols', ['goal', 'target']),
];
